### ISSUE TITLE
Cannot run app

### ISSUE THREAD

**Issue by zukalous** [ooper-shlab/Breadcrumb4.1-Swift#2]
Hi I just downloaded the source code and ran it and I get a ton of errors. 

In BreadcrumbViewController.swift, private func DescriptionOfCLAuthorizationStatus
I get a bunch of errors "Extraneous '.' in enum 'case' declaration for each item in the case statement. 

Also in settingsDidChange I get a "Use of unresolved identifier 'UserDefaults' in this line 
  let settings = UserDefaults.standard

I am getting so many errors I am wondering if I have the settings of xcode right. Can you let me know if I have to be in some different mode or something?

Using xcode ver 7.3.1

**Comment by ooper-shlab** [comment]
Thanks for having interested in my translation of the sample code. This sample code is already updated to Swift 3, so you cannot run or build it with Xcode 7.3.1 . (Please read readme.txt .)

Please try with the latest released version of Xcode, or clone the repository and retrieve the Swift 2 version from the history.

**Comment by zukalous** [comment]
Oh man I feel dumb. I had the wrong version of xcode. I guess if you have the old version you can only update it so far before you have to donwload the latest version. Your code works great now that I have the right version :).  Thanks for doing this.
